// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Db;

#nullable disable

namespace ShoppingCart.Migrations
{
    [DbContext(typeof(ShoppingCartDb))]
    [Migration("20260504131802_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ShoppingCart.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fefe38a-a237-40cb-a7d9-888cd52bbffa"),
                            Name = "Product1",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("5c91f906-b10e-4686-9c9b-cb39fd520de8"),
                            Name = "Product2",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("aeafbc3a-6b55-4bf6-ba5a-8350e20db908"),
                            Name = "Product3",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("df36e4d1-dd05-4363-a28d-8adf42790ab6"),
                            Name = "Product4",
                            Price = 400m
                        },
                        new
                        {
                            Id = new Guid("f2ebeef4-6c76-46bb-8036-816bb5890d34"),
                            Name = "Product5",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("f34747f7-3d6d-4484-8c58-55e8ac69f7ab"),
                            Name = "Product6",
                            Price = 600m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
